---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-role
  namespace: jobs-test
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create"]
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-role-binding
  namespace: jobs-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: jobs-test
